export const DATA_TEST = {
  "response":{
    "numFound":10,
    "start":0,
    "numFoundExact":true,
    "docs":[{
      "title_s":["Tensor Decompositions for Signal Processing: Theory, Advances, and Applications"],
      "keyword_s":["Tensor decompositions","Low rank approximations","Network compression","Wireless communication","Remote sensing","Tensor completion"],
      "abstract_s":["In the era of big data, rapid advancements in technology and data collection methods have led to the generation and accessibility of vast amounts of multi-modal, high-dimensional data across a diverse range of disciplines. Tensor methods have emerged as essential tools in signal processing, providing powerful frameworks to model and analyze such complex data effectively. This survey offers a comprehensive overview of tensor factorization techniques and their applications in key areas. We explore their role in remote sensing, focusing on tensor-based methods for analyzing hyperspectral and multispectral images, tackling challenges such as recovering super-resolution images and addressing spectral unmixing. In wireless communication, we examine tensor methods used for signal modulation in unsourced massive random access communication, which achieve strong performance in multi-antenna channel and signal modeling. We also discuss tensor applications in network compression, where they reduce the computational demands of deep neural networks, making them more feasible for edge devices. Additionally, we highlight the use of tensor methods in high-dimensional missing data completion problems, showcasing their versatility across various domains. Furthermore, we explore applications in image analysis and computer vision, where tensors are effectively utilized for motion and object tracking, 3D modeling, analysis of satellite imaging, and medical imaging. By bridging theoretical advancements with practical applications, this survey aims to guide researchers in leveraging tensor methods to tackle emerging challenges in signal processing."],
      "journalTitle_s":"Signal Processing",
      "authFullName_s":["Neriman Tokcan","Shakir Showkat Sofi","Van Tien Pham","Clémence Prévost","Sofiane Kharbech","Baptiste Magnier","Thanh Phuong Nguyen","Yassine Zniyed","Lieven de Lathauwer"],
      "uri_s":"https://hal.science/hal-05135784v2",
      "producedDateY_i":2026
    },{
      "title_s":["Exploring the Role of Stigma and Reduced Facial Expressions in Shaping First Impressions of Individuals with Schizophrenia"],
      "abstract_s":["Abstract Background and Hypothesis First impressions are rapid judgments based on limited information, significantly influencing one’s willingness to interact. Social difficulties in schizophrenia may stem from negative first impressions formed by healthy individuals. We hypothesized that healthy individuals would quickly develop negative first impressions of those with schizophrenia, driven in part by reduced facial expressions and stigma. Study Design Twenty individuals with schizophrenia and 20 age- and sex-matched healthy controls were filmed responding to a question for 30 seconds. Three hundred participants from the general population rated their first impressions of the 40 video recordings. The diagnosis of individuals with schizophrenia was either retained, disclosed, or misrepresented as autistic. To isolate the effect of facial expressions, stimuli were presented without sound using a point light display. Study Results Individuals with schizophrenia received more negative first impression ratings than healthy controls, and higher negative symptoms were linked to poorer first impression ratings. OpenFace analysis confirmed that facial expressions significantly shaped impressions, particularly mouth movement. Additionally, ratings worsened when participants’ schizophrenia diagnosis was disclosed, highlighting the harmful impact of stigma. Conversely, when mislabeled as having autism, first impression ratings improved. Conclusions This study highlights the compounded negative effects of facial expressions and schizophrenia-related stigma on first impressions. Given their significant influence on social interactions, future research should explore strategies to mitigate these effects."],
      "journalTitle_s":"Schizophrenia Bulletin",
      "authFullName_s":["Mathilde Parisi","Ludovic Marin","Juliette Lozano-Goupil","Tifenn Fauviaux","Victor Vattier","Delphine Capdevielle","Stéphane Raffard"],
      "uri_s":"https://hal.science/hal-05338796v1",
      "producedDateY_i":2025
    },{
      "title_s":["“The second I laid eyes on him I knew”: First impressions predict willingness to interact with individuals with schizophrenia"],
      "abstract_s":["Individuals diagnosed with schizophrenia encounter significant challenges in their daily social interactions. These deficits emphasize neurocognitive disabilities, impaired social cognition, and stigma. However, social presentation especially public perception of patients’ social behavior has been poorly studied to date in this mental disorder despite the fundamental importance of first impression in human interaction. This study aims to investigate whether a schizophrenia patient leads to a lower first impression than a depressive individual and a healthy control when there is no diagnostic label, and on which features these first impressions are created. We extracted nonverbal behavioral measures from thin slice of social behaviour of the stimulus participants and presented audio and/or video clips to naive observers. We found that the general population had significantly more negative impressions and behavioral intentions to interact with the schizophrenia patient than the depressive and the control participant, regardless of the modality presented. As patients displayed fewer nonverbal behaviors, it suggests that social behavior drives first impression in schizophrenia. Such findings may lead to new ways of developing intervention programs targeting motor nonverbal behavior, leading to reduce social rejection in these populations."],
      "journalTitle_s":"Schizophrenia Research",
      "authFullName_s":["Tifenn Fauviaux","Mathilde Parisi","Ludovic Marin","Victor Vattier","Juliette Lozano-Goupil","Dorra Mrabet","Delphine Capdevielle","Stéphane Raffard"],
      "uri_s":"https://hal.science/hal-05338793v1",
      "producedDateY_i":2025
    },{
      "title_s":["Attitudes, self-efficacy and behavioral intentions to exercise with a socially assistive robot in individuals with schizophrenia: An exploratory study"],
      "abstract_s":["Individuals with schizophrenia generally engage in significantly less physical activities in comparison with the general population, partly due to motivation deficits, but also structural barriers such as lack of available qualified health professionals. One solution is to use social robots to facilitate engagement in exercise. This research has a dual focus: first, comparing attitudes, self-efficacy, and behavioral intentions towards engaging in exercise with NAO between individuals with schizophrenia and healthy controls; second, assessing the impact of interpersonal coordination between the robot and human on intention to engage in exercise in both groups. In this study based on health Behaviour Change Theories, 22 participants with schizophrenia were matched with 24 nonclinical participants. Physical activities were conducted with NAO under two conditions: Synchronizing (NAO is adaptive to the participant’s rhythm) and Not-Synchronizing (non-adaptive). Participants completed questionnaires measuring attitudes, self-efficacy, and intention to engage in exercise with NAO after each condition. Results indicated that both groups held generally positive attitudes towards exercise with NAO. However, individuals with schizophrenia reported lower self-efficacy compared to control participants but similar behavioral intention to engage in exercise with NAO than control participants. Behavioral intention subscales were positively correlated with positive attitudes and self-efficacy. This study contributes to the increased efforts to develop new technologies for use in mental health care interventions for adults with severe mental disorders. Finally, we will discuss the potentials and limitations of using social robots to promote exercise in individuals with schizophrenia."],
      "journalTitle_s":"The International Journal of Robotics Research",
      "authFullName_s":["Stéphane Raffard","Juliette Lozano-Goupil","Richard Schmidt","Ludovic Marin","Julie Boiché","Cindy Lebrun","Lise Aubin","Amandine Decombe","Helene Serre","Delphine Capdevielle","Ghiles Mostafaoui"],
      "uri_s":"https://hal.science/hal-05338788v1",
      "producedDateY_i":2025
    },{
      "title_s":["SkeltyMLOps: Orchestrating Collaborative MLOps Activities"],
      "keyword_s":["Orchestration","Collaborative MLOps","MLOps Reference Architecture","MLOps Activities","MLOps Actors","Machine Learning Operations","Software Engineering"],
      "abstract_s":["With the increasing adoption of machine learning (ML), the need to manage, in a tailored manner, the complete lifecycle of this new type of software arises. MLOps (Machine Learning Operations) extends DevOps to address the specific challenges of development and lifelong management of ML-powered software. Despite the increasing attention to this domain, practitioners still lack an accessible, modular architecture to support MLOps projects. To address this lack, this paper proposes SkeltyMLOps, a reference architecture designed to promote collaboration between the diverse actors involved in MLOps processes. The architecture is derived from a thorough literature review, from which we extracted and clustered, using a Large Language Model (LLM), a comprehensive list of MLOps actors and activities. These clusters were then used to guide the architectural decomposition and component design of SkeltyMLOps. The originality of our proposed reference architecture is (i) that it clearly aligns its components with the responsibilities of MLOps actors, covering the identified dimensions of MLOps processes, and (ii) mediates collaboration by orchestrating interactions between the different types of actors. This architecture provides a foundation for building collaborative ML-powered software."],
      "conferenceTitle_s":"MLOps25 - Workshop on Machine Learning Operations / the 1st ECAI Workshop on MLOps",
      "authFullName_s":["Charbel Daoud","Danielle Azar","Julie Boiché","Christelle Urtado","Sylvain Vauttier"],
      "uri_s":"https://hal.science/hal-05337700v1",
      "producedDateY_i":2025
    },{
      "title_s":["Comprehensive Review of Open-Source Fundus Image Databases for Diabetic Retinopathy Diagnosis"],
      "keyword_s":["Computer science image analysis","Databases","Fundus image","Diabetic retinopathy"],
      "abstract_s":["Databases play a crucial role in training, validating, and comparing AI models for detecting retinal diseases, as well as in clinical research, technology development, and healthcare professional training. Diabetic retinopathy (DR), a common diabetes complication, is a leading cause of vision impairment and blindness worldwide. Early detection and management are essential to prevent irreversible vision loss. Fundus photography, known for being economical and non-contact, is a widely applicable gold standard method that offers a convenient way to diagnose and grade DR. This paper presents a comprehensive review of 22 open-source fundus retinal image databases commonly used in DR research, highlighting their main characteristics and key features. Most of these datasets were released between 2000 and 2022. These databases are analyzed through an in-depth examination of their images, enabling objective comparison using color space distances and Principal Component Analysis (PCA) based on 16 key statistical features. Finally, this review aims to support informed decision-making for researchers and practitioners involved in DR diagnosis and management, ultimately improving patient outcomes."],
      "journalTitle_s":"Sensors",
      "authFullName_s":["Valérian Conquer","Thomas Lambolais","Gustavo Andrade-Miranda","Baptiste Magnier"],
      "uri_s":"https://imt-mines-ales.hal.science/hal-05335049v1",
      "producedDateY_i":2025
    },{
      "title_s":["Spiking neural networks for multimodal dance performance classification"],
      "keyword_s":["Classification Multimodale","Spiking Neural Network","Dance"],
      "abstract_s":["This study focuses on human synchronization in dance: how individuals adapt their movements when dancing to music with a partner. We analyze a dataset of dyadic dance, where pairs of individuals performed in four experimental conditions either listening to the same or different music and either seeing each other or not. The individuals' whole-body movements were recorded using 22 motion capture sensors. A key question we investigate is whether motion alone can reveal the condition in which the dancers were recorded. To address this classification problem, we use Spiking Neural Networks (SNNs). Due to their intrinsic ability to encode temporal dynamics, these models seem well suited for analyzing such motion time series data. Since SNNs process discrete spike events, an essential preprocessing step involves encoding continuous movement data into spikes. Classification accuracy is evaluated through various preprocessing steps, network architectures and hyperparameters. The results open perspectives for a biologically plausible modeling of human perception of synchronization."],
      "conferenceTitle_s":"TMD 2025 - Team and Multi-Agent Dynamics in Digital and Physical Realities",
      "authFullName_s":["Théo Velletaz","Stefan Janaqi","Sébastien Harispe","Patrice Guyot"],
      "uri_s":"https://imt-mines-ales.hal.science/hal-05326441v1",
      "producedDateY_i":2025
    },{
      "title_s":["Modeling the Dynamics of Approach and Avoidance Motivation in Achievement Context with an Agent-based Model"],
      "keyword_s":["Pink Noise","Computer Simulation","Attractor","Achievement Goal","Achievement Motivation"],
      "abstract_s":["The shape of the corresponding attractor landscape is assumed to evolve over time through interactions among three necessary and sufficient social-cognitive variables, namely competence expectancies, expected benefit for the self, and threat for the self. These variables interact within and across personal, contextual, and situational levels. The present study aimed to (a) develop an Agent-Based Models (ABM; Smaldino, 2023) capable of simulating these interactions and therefore the dynamics of approach and avoidance motivation patterns, and (b) compare the outputs of this ABM with longitudinal data from three athletes and two PhD students pursuing an important mid-term (1–2 years) goal. Whittle's Maximum Likelihood Estimator (Roume, 2023) was used to detect 1/f power-law distributions—a temporal variability typical of complex dynamical phenomena—in the time series of both simulation and ecological data. Findings revealed 1/f distributions in both types of time series, thus supporting the relevance of the CDS paradigm in understanding approach and avoidance motivation. They also pave the way for future research testing intervention hypotheses on motivation using computer simulation."],
      "conferenceTitle_s":"TMD 2025 - Team and Multi-Agent Dynamics in Digital and Physical Realities",
      "authFullName_s":["Rémi Altamore","Sylvain Vauttier","Anne Teboul","Ruud J.R. den Hartigh","Paul L. C. van Geert","C. Gernigon"],
      "uri_s":"https://imt-mines-ales.hal.science/hal-05326414v1",
      "producedDateY_i":2025
    },{
      "title_s":["Enculturation's Rhythmic Imprint: Cross-Cultural Variations in Sensorimotor Synchronization"],
      "keyword_s":["Model-based","Sensorimotor Synchronization","Cross-cultural"],
      "abstract_s":["Group dynamics are more than a mere aggregation of individual behaviors; they emerge from the complex interplay interactions, which are deeply context dependent. Notably, a growing body of literature shows that enculturation introduces variations, as the rhythmic exposure since childhood shapes how individual synchronize their actions. Thereby, cultural environment molds group dynamics by influencing the most basic element of interpersonal interactions: individual perception-action dynamics. To examine this influence, we conducted two experiments to identify cross-cultural variations between French and Indian participants engaging in classical synchronization tasks. The results were analyzed through the lens of the dynamical system approach using forced oscillator models. In the first study, we documented the synchronization dynamics of both groups. The results revealed that while French participants exhibited negative mean asynchrony, Indian participants had a positive mean asynchrony. We proposed that this difference was partly due to a bigger over-estimation of the frequency of the rhythm for French participants than for Indian participants. In the second study, we explored the frequency adaptation mechanism supposed to be the cause of the observed over-estimation. Overall, our findings suggests that enculturation imprints down our most elementary temporal neural functions, thereby modifying our rhythmic behaviors and altering group dynamics."],
      "conferenceTitle_s":"TMD 2025 - Team and Multi-Agent Dynamics in Digital and Physical Realities",
      "authFullName_s":["Martin Le Guennec","Andon Tchechmedjiev","Julien Lagarde"],
      "uri_s":"https://imt-mines-ales.hal.science/hal-05326393v1",
      "producedDateY_i":2025
    },{
      "title_s":["Interbrain synchrony trajectories during teamwork"],
      "keyword_s":["Developmental Dynamics","Trajectory over time","Teamwork","Hyperscanning","Interbrain Synchrony"],
      "abstract_s":["Theoretical models posit that teamwork, the social interaction in which individuals collaborate to reach a common goal, matures and progresses during a task episode. Due to the limitations of the traditional psychological tools (i.e. questionnaires), this evolution of teamwork has never been verified. As inter-brain synchrony (IBS), the degree of similarity between individuals' brain activity, appears to be a relevant measure of teamwork, we used IBS to examine its trajectories during a task episode. We hypothesised that IBS would increase over time. Forty dyads completed a 30-minute cooperative task with asymmetric roles. fNIRS hyperscanning recorded brain activity in six regions within the prefrontal and temporoparietal areas. IBS was quantified using wavelet transform coherence. Linear mixed models, with time as a fixed effect, slope and intercept as random effects for dyads tested the effect of time on IBS. Control analyses using permuted dyads confirmed IBS appearance during teamwork. No significant effect of time on IBS was found; however, there was significant heterogeneity in IBS trajectories between teams. There is no overall increase or decrease in IBS in the sample. Further research is needed to understand why some teams show an increase in IBS over time, while others show a decrease."],
      "conferenceTitle_s":"TMD 2025 - Team and Multi-Agent Dynamics in Digital and Physical Realities",
      "authFullName_s":["Coralie Réveillé","Grégoire Vergotte","S. Perrey","Gérard Dray","Pierre-Antoine Jean","Grégoire Bosselut"],
      "uri_s":"https://imt-mines-ales.hal.science/hal-05326384v1",
      "producedDateY_i":2025
    }]
  }
}